import {
  ShoppingBag,
  Coffee,
  Car,
  Home,
  HeartPulse,
  Gamepad2,
  Smartphone,
  Plane,
  Gift,
  HelpCircle,
  Briefcase,
  TrendingUp,
  Banknote,
} from 'lucide-react';

export const PERSONAL_CATEGORIES = {
  'Food & Others': {
    label: 'Courses & Divers',
    icon: ShoppingBag,
    color: 'text-orange-400',
    bg: 'bg-orange-400/10',
    border: 'border-orange-400/20',
  },
  Restaurants: {
    label: 'Restaurants & Sorties',
    icon: Coffee,
    color: 'text-yellow-400',
    bg: 'bg-yellow-400/10',
    border: 'border-yellow-400/20',
  },
  Entertainment: {
    label: 'Loisirs',
    icon: Gamepad2,
    color: 'text-purple-400',
    bg: 'bg-purple-400/10',
    border: 'border-purple-400/20',
  },
  Tech: {
    label: 'Tech / Services',
    icon: Smartphone,
    color: 'text-gray-300',
    bg: 'bg-gray-300/10',
    border: 'border-gray-500/20',
  },
  Transport: {
    label: 'Transport',
    icon: Car,
    color: 'text-blue-400',
    bg: 'bg-blue-400/10',
    border: 'border-blue-400/20',
  },
  Housing: {
    label: 'Logement & Charges',
    icon: Home,
    color: 'text-indigo-400',
    bg: 'bg-indigo-400/10',
    border: 'border-indigo-400/20',
  },
  Health: {
    label: 'Santé',
    icon: HeartPulse,
    color: 'text-red-400',
    bg: 'bg-red-400/10',
    border: 'border-red-400/20',
  },
  Travel: {
    label: 'Voyage',
    icon: Plane,
    color: 'text-cyan-400',
    bg: 'bg-cyan-400/10',
    border: 'border-cyan-400/20',
  },
  Gift: {
    label: 'Cadeaux',
    icon: Gift,
    color: 'text-emerald-400',
    bg: 'bg-emerald-400/10',
    border: 'border-emerald-400/20',
  },
  Salary: {
    label: 'Salaire & Revenus',
    icon: Banknote,
    color: 'text-emerald-400',
    bg: 'bg-emerald-400/10',
    border: 'border-emerald-400/20',
  },
  Business: {
    label: 'Pro (Virement)',
    icon: Briefcase,
    color: 'text-gray-200',
    bg: 'bg-gray-700/50',
    border: 'border-gray-600',
  },
  Invest: {
    label: 'Investissement',
    icon: TrendingUp,
    color: 'text-emerald-500',
    bg: 'bg-emerald-900/20',
    border: 'border-emerald-500/30',
  },
  Divers: {
    label: 'Autre',
    icon: HelpCircle,
    color: 'text-gray-400',
    bg: 'bg-gray-400/10',
    border: 'border-gray-400/20',
  },
};
